# Generated by Django 4.2.5 on 2023-09-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0003_customuser_alter_postmodel_author_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
